import type {
  TelegramSchemaField,
  TelegramSchemaIr,
  TelegramSchemaPrimitive,
  TelegramSchemaType,
} from './ir.ts';

/**
 * Renders the Telegram Bot API's wire-format TypeScript declarations.
 *
 * The output deliberately preserves Telegram field names. The public camelCase
 * layer is generated separately so serializers can always target this stable
 * representation without ambiguity.
 */
export function generateTelegramWireTypes(ir: TelegramSchemaIr): string {
  const lines = [
    '/* eslint-disable */',
    '// This file is generated by scripts/telegram-schema/generate.ts.',
    '// Do not edit it manually; update the checked-in schema snapshot instead.',
    `// Telegram Bot API version: ${ir.apiVersion}.`,
    '',
    '/** A value accepted by Telegram as a new file upload. */',
    'export interface InputFile {',
    '  readonly __telegrabunInputFileBrand: unique symbol;',
    '}',
    '',
  ];

  for (const object of ir.objects) {
    lines.push(`export interface ${object.name} {`, ...renderFields(object.fields), '}', '');
  }

  for (const union of ir.unions) {
    lines.push(`export type ${union.name} = ${renderUnionMembers(union.members)};`, '');
  }

  for (const method of ir.methods) {
    const typeName = toPascalCase(method.name);
    lines.push(
      `export interface ${typeName}Params {`,
      ...renderFields(method.parameters),
      '}',
      '',
      `export type ${typeName}Result = ${renderType(method.result)};`,
      '',
    );
  }

  return `${lines.join('\n')}\n`;
}

/**
 * Renders the ergonomic TypeScript declarations used by the public API.
 *
 * Telegram's schema uses snake_case, while the library accepts and returns
 * camelCase values. This generator mirrors every object and union instead of
 * applying a mapped type at the use site, so consumers get readable
 * declarations and discriminated unions retain their literal discriminators.
 */
export function generateTelegramPublicTypes(ir: TelegramSchemaIr): string {
  const lines = [
    '/* eslint-disable */',
    '// This file is generated by scripts/telegram-schema/generate.ts.',
    '// Do not edit it manually; update the checked-in schema snapshot instead.',
    `// Telegram Bot API version: ${ir.apiVersion}.`,
    '',
    '/** A value accepted by Telegram as a new file upload. */',
    "export type InputFile = import('./wire.ts').InputFile;",
    '',
  ];

  for (const object of ir.objects) {
    lines.push(`export interface ${object.name} {`, ...renderPublicFields(object.fields), '}', '');
  }

  for (const union of ir.unions) {
    lines.push(`export type ${union.name} = ${renderUnionMembers(union.members)};`, '');
  }

  for (const method of ir.methods) {
    const typeName = toPascalCase(method.name);
    lines.push(
      `export interface ${typeName}Params {`,
      ...renderPublicFields(method.parameters),
      '}',
      '',
      `export type ${typeName}Result = ${renderType(method.result)};`,
      '',
    );
  }

  lines.push('export interface ApiMethodMap {');
  for (const method of ir.methods) {
    const typeName = toPascalCase(method.name);
    lines.push(
      `  readonly ${method.name}: {`,
      `    readonly params: ${typeName}Params;`,
      `    readonly result: ${typeName}Result;`,
      '  };',
    );
  }
  lines.push(
    '}',
    '',
    'export type ApiMethodName = keyof ApiMethodMap;',
    '',
    "export type ApiMethodParams<Method extends ApiMethodName> = ApiMethodMap[Method]['params'];",
    '',
    "export type ApiMethodResult<Method extends ApiMethodName> = ApiMethodMap[Method]['result'];",
    '',
  );

  return `${lines.join('\n')}\n`;
}

function renderFields(fields: readonly TelegramSchemaField[]): string[] {
  return fields.map(
    (field) => `  readonly ${field.name}${field.required ? '' : '?'}: ${renderType(field.type)};`,
  );
}

function renderPublicFields(fields: readonly TelegramSchemaField[]): string[] {
  return fields.map(
    (field) =>
      `  readonly ${toCamelCase(field.name)}${field.required ? '' : '?'}: ${renderType(field.type)};`,
  );
}

function renderUnionMembers(members: readonly TelegramSchemaType[]): string {
  return members.map(renderType).join(' | ');
}

function renderType(type: TelegramSchemaType): string {
  switch (type.kind) {
    case 'array':
      return `ReadonlyArray<${renderType(type.element)}>`;
    case 'input-file':
      return 'InputFile';
    case 'literal':
      return JSON.stringify(type.value);
    case 'primitive':
      return renderPrimitive(type.name);
    case 'reference':
      return type.name;
    case 'union':
      return renderUnionMembers(type.members);
  }
}

function renderPrimitive(name: TelegramSchemaPrimitive): string {
  switch (name) {
    case 'boolean':
      return 'boolean';
    case 'float':
    case 'integer':
      return 'number';
    case 'string':
      return 'string';
    case 'true':
      return 'true';
  }
}

function toPascalCase(name: string): string {
  return `${name[0]!.toUpperCase()}${name.slice(1)}`;
}

function toCamelCase(name: string): string {
  return name.replace(/_([a-z0-9])/g, (_, character: string) => character.toUpperCase());
}
