import type {
  TelegramSchemaField,
  TelegramSchemaIr,
  TelegramSchemaPrimitive,
  TelegramSchemaType,
} from './ir.ts';
import type { TelegramSchemaSnapshotMetadata } from './verify-snapshot.ts';

/**
 * Renders the Telegram Bot API's wire-format TypeScript declarations.
 *
 * The output deliberately preserves Telegram field names. The public camelCase
 * layer is generated separately so serializers can always target this stable
 * representation without ambiguity.
 */
export function generateTelegramWireTypes(ir: TelegramSchemaIr): string {
  const lines = [
    '/* eslint-disable */',
    '// This file is generated by scripts/telegram-schema/generate.ts.',
    '// Do not edit it manually; update the checked-in schema snapshot instead.',
    `// Telegram Bot API version: ${ir.apiVersion}.`,
    '',
    '/** A value accepted by Telegram as a new file upload. */',
    'export interface InputFile {',
    '  readonly __telegrabunInputFileBrand: unique symbol;',
    '}',
    '',
  ];

  for (const object of ir.objects) {
    lines.push(`export interface ${object.name} {`, ...renderFields(object.fields), '}', '');
  }

  for (const union of ir.unions) {
    lines.push(`export type ${union.name} = ${renderUnionMembers(union.members)};`, '');
  }

  for (const method of ir.methods) {
    const typeName = toPascalCase(method.name);
    lines.push(
      `export interface ${typeName}Params {`,
      ...renderFields(method.parameters),
      '}',
      '',
      `export type ${typeName}Result = ${renderType(method.result)};`,
      '',
    );
  }

  return `${lines.join('\n')}\n`;
}

/**
 * Renders the ergonomic TypeScript declarations used by the public API.
 *
 * Telegram's schema uses snake_case, while the library accepts and returns
 * camelCase values. This generator mirrors every object and union instead of
 * applying a mapped type at the use site, so consumers get readable
 * declarations and discriminated unions retain their literal discriminators.
 */
export function generateTelegramPublicTypes(ir: TelegramSchemaIr): string {
  const lines = [
    '/* eslint-disable */',
    '// This file is generated by scripts/telegram-schema/generate.ts.',
    '// Do not edit it manually; update the checked-in schema snapshot instead.',
    `// Telegram Bot API version: ${ir.apiVersion}.`,
    '',
    '/** A value accepted by Telegram as a new file upload. */',
    "export type InputFile = import('./wire.ts').InputFile;",
    '',
  ];

  for (const object of ir.objects) {
    lines.push(`export interface ${object.name} {`, ...renderPublicFields(object.fields), '}', '');
  }

  for (const union of ir.unions) {
    lines.push(`export type ${union.name} = ${renderUnionMembers(union.members)};`, '');
  }

  for (const method of ir.methods) {
    const typeName = toPascalCase(method.name);
    lines.push(
      `export interface ${typeName}Params {`,
      ...renderPublicFields(method.parameters),
      '}',
      '',
      `export type ${typeName}Result = ${renderType(method.result)};`,
      '',
    );
  }

  lines.push('export interface ApiMethodMap {');
  for (const method of ir.methods) {
    const typeName = toPascalCase(method.name);
    lines.push(
      `  readonly ${method.name}: {`,
      `    readonly params: ${typeName}Params;`,
      `    readonly result: ${typeName}Result;`,
      '  };',
    );
  }
  lines.push(
    '}',
    '',
    'export type ApiMethodName = keyof ApiMethodMap;',
    '',
    "export type ApiMethodParams<Method extends ApiMethodName> = ApiMethodMap[Method]['params'];",
    '',
    "export type ApiMethodResult<Method extends ApiMethodName> = ApiMethodMap[Method]['result'];",
    '',
  );

  return `${lines.join('\n')}\n`;
}

/**
 * Renders named, typed Bot API methods that delegate to the handwritten core.
 *
 * The generated facade makes every method discoverable as `api.sendMessage(...)`
 * while serialization and transport remain in the shared, testable core. Methods
 * without required parameters omit the argument when called without options.
 */
export function generateTelegramApiClient(ir: TelegramSchemaIr): string {
  const lines = [
    '/* eslint-disable */',
    '// This file is generated by scripts/telegram-schema/generate.ts.',
    '// Do not edit it manually; update the checked-in schema snapshot instead.',
    `// Telegram Bot API version: ${ir.apiVersion}.`,
    '',
    "import { ApiClientCore } from '../api/client-core.ts';",
    '',
    "import type * as Public from './public.ts';",
    '',
    '/** Named, type-safe Telegram Bot API methods backed by ApiClientCore. */',
    'export class Api {',
    '  readonly #core: ApiClientCore;',
    '',
    '  constructor(core: ApiClientCore) {',
    '    this.#core = core;',
    '  }',
    '',
  ];

  for (const method of ir.methods) {
    const typeName = toPascalCase(method.name);
    if (method.parameters.length === 0) {
      lines.push(
        `  ${method.name}(): Promise<Public.${typeName}Result> {`,
        `    return this.#core.call('${method.name}', {});`,
        '  }',
        '',
      );
    } else if (method.parameters.some((parameter) => parameter.required)) {
      lines.push(
        `  ${method.name}(params: Public.${typeName}Params): Promise<Public.${typeName}Result> {`,
        `    return this.#core.call('${method.name}', params);`,
        '  }',
        '',
      );
    } else {
      lines.push(
        `  ${method.name}(params: Public.${typeName}Params = {}): Promise<Public.${typeName}Result> {`,
        `    return this.#core.call('${method.name}', params);`,
        '  }',
        '',
      );
    }
  }

  lines.push('}');
  return `${lines.join('\n')}\n`;
}

/**
 * Renders the runtime schema consumed by the serializer layer.
 *
 * It keeps both public camelCase and Telegram wire names, plus the complete
 * type tree needed to discover nested InputFile values without consulting
 * TypeScript declarations at runtime.
 */
export function generateTelegramRuntimeMetadata(
  ir: TelegramSchemaIr,
  snapshot: TelegramSchemaSnapshotMetadata,
): string {
  if (snapshot.api.version !== ir.apiVersion) {
    throw new Error(
      `Telegram schema snapshot API version ${snapshot.api.version} does not match IR API version ${ir.apiVersion}.`,
    );
  }
  const typeDefinitions = new Map<string, readonly TelegramSchemaType[]>();
  for (const object of ir.objects) {
    typeDefinitions.set(
      object.name,
      object.fields.map((field) => field.type),
    );
  }
  for (const union of ir.unions) {
    typeDefinitions.set(union.name, union.members);
  }

  const lines = [
    '/* eslint-disable */',
    '// This file is generated by scripts/telegram-schema/generate.ts.',
    '// Do not edit it manually; update the checked-in schema snapshot instead.',
    `// Telegram Bot API version: ${ir.apiVersion}.`,
    '',
    'export type TelegramApiRuntimeType =',
    "  | { readonly kind: 'array'; readonly element: TelegramApiRuntimeType }",
    "  | { readonly kind: 'input-file' }",
    "  | { readonly kind: 'literal' }",
    "  | { readonly kind: 'primitive' }",
    "  | { readonly kind: 'reference'; readonly name: string }",
    "  | { readonly kind: 'union'; readonly members: readonly TelegramApiRuntimeType[] };",
    '',
    'export interface TelegramApiRuntimeField {',
    '  readonly name: string;',
    '  readonly wireName: string;',
    '  readonly required: boolean;',
    '  readonly containsInputFile: boolean;',
    '  readonly type: TelegramApiRuntimeType;',
    '}',
    '',
    'export interface TelegramApiRuntimeObject {',
    '  readonly fields: readonly TelegramApiRuntimeField[];',
    '}',
    '',
    'export interface TelegramApiRuntimeUnion {',
    '  readonly members: readonly TelegramApiRuntimeType[];',
    '  readonly discriminator?: {',
    '    readonly name: string;',
    '    readonly wireName: string;',
    '  };',
    '}',
    '',
    'export interface TelegramApiRuntimeMethod {',
    '  readonly parameters: readonly TelegramApiRuntimeField[];',
    '  readonly result: TelegramApiRuntimeType;',
    '}',
    '',
    'export interface TelegramApiRuntimeMetadata {',
    '  readonly schemaFormatVersion: number;',
    '  readonly api: {',
    '    readonly version: string;',
    '    readonly announcedAt: string;',
    '  };',
    '  readonly source: {',
    '    readonly url: string;',
    '    readonly retrievedAt: string;',
    '  };',
    '  readonly snapshot: {',
    '    readonly path: string;',
    '    readonly sha256: string;',
    '    readonly bytes: number;',
    '  };',
    '  readonly objects: Readonly<Record<string, TelegramApiRuntimeObject>>;',
    '  readonly unions: Readonly<Record<string, TelegramApiRuntimeUnion>>;',
    '  readonly methods: Readonly<Record<string, TelegramApiRuntimeMethod>>;',
    '}',
    '',
    'export const telegramApiMetadata = {',
    `  schemaFormatVersion: ${ir.formatVersion},`,
    '  api: {',
    `    version: ${JSON.stringify(snapshot.api.version)},`,
    `    announcedAt: ${JSON.stringify(snapshot.api.announcedAt)},`,
    '  },',
    '  source: {',
    `    url: ${JSON.stringify(snapshot.source.url)},`,
    `    retrievedAt: ${JSON.stringify(snapshot.source.retrievedAt)},`,
    '  },',
    '  snapshot: {',
    `    path: ${JSON.stringify(snapshot.snapshot.path)},`,
    `    sha256: ${JSON.stringify(snapshot.snapshot.sha256)},`,
    `    bytes: ${snapshot.snapshot.bytes},`,
    '  },',
    '  objects: {',
  ];

  for (const object of ir.objects) {
    lines.push(`    ${JSON.stringify(object.name)}: {`, '      fields: [');
    lines.push(...renderRuntimeFields(object.fields, 8, typeDefinitions));
    lines.push('      ],', '    },');
  }

  lines.push('  },', '  unions: {');
  for (const union of ir.unions) {
    lines.push(`    ${JSON.stringify(union.name)}: {`, '      members: [');
    lines.push(...renderRuntimeTypes(union.members, 8));
    lines.push('      ],');
    if (union.discriminator !== undefined) {
      lines.push(
        '      discriminator: {',
        `        name: ${JSON.stringify(toCamelCase(union.discriminator.field))},`,
        `        wireName: ${JSON.stringify(union.discriminator.field)},`,
        '      },',
      );
    }
    lines.push('    },');
  }

  lines.push('  },', '  methods: {');
  for (const method of ir.methods) {
    lines.push(`    ${JSON.stringify(method.name)}: {`, '      parameters: [');
    lines.push(...renderRuntimeFields(method.parameters, 8, typeDefinitions));
    lines.push('      ],', '      result:');
    lines.push(...renderRuntimeType(method.result, 8));
    lines.push('    },');
  }

  lines.push('  },', '} as const satisfies TelegramApiRuntimeMetadata;', '');
  return `${lines.join('\n')}\n`;
}

function renderFields(fields: readonly TelegramSchemaField[]): string[] {
  return fields.map(
    (field) => `  readonly ${field.name}${field.required ? '' : '?'}: ${renderType(field.type)};`,
  );
}

function renderPublicFields(fields: readonly TelegramSchemaField[]): string[] {
  return fields.map(
    (field) =>
      `  readonly ${toCamelCase(field.name)}${field.required ? '' : '?'}: ${renderType(field.type)};`,
  );
}

function renderRuntimeFields(
  fields: readonly TelegramSchemaField[],
  indent: number,
  typeDefinitions: ReadonlyMap<string, readonly TelegramSchemaType[]>,
): string[] {
  return fields.flatMap((field) => [
    `${' '.repeat(indent)}{`,
    `${' '.repeat(indent + 2)}name: ${JSON.stringify(toCamelCase(field.name))},`,
    `${' '.repeat(indent + 2)}wireName: ${JSON.stringify(field.name)},`,
    `${' '.repeat(indent + 2)}required: ${field.required},`,
    `${' '.repeat(indent + 2)}containsInputFile: ${containsInputFile(field.type, typeDefinitions)},`,
    `${' '.repeat(indent + 2)}type:`,
    ...renderRuntimeType(field.type, indent + 4),
    `${' '.repeat(indent)}},`,
  ]);
}

function renderRuntimeTypes(types: readonly TelegramSchemaType[], indent: number): string[] {
  return types.flatMap((type) => renderRuntimeType(type, indent));
}

function renderRuntimeType(type: TelegramSchemaType, indent: number): string[] {
  const padding = ' '.repeat(indent);
  switch (type.kind) {
    case 'array':
      return [
        `${padding}{`,
        `${padding}  kind: 'array',`,
        `${padding}  element:`,
        ...renderRuntimeType(type.element, indent + 4),
        `${padding}},`,
      ];
    case 'input-file':
      return [`${padding}{ kind: 'input-file' },`];
    case 'literal':
      return [`${padding}{ kind: 'literal' },`];
    case 'primitive':
      return [`${padding}{ kind: 'primitive' },`];
    case 'reference':
      return [`${padding}{ kind: 'reference', name: ${JSON.stringify(type.name)} },`];
    case 'union':
      return [
        `${padding}{`,
        `${padding}  kind: 'union',`,
        `${padding}  members: [`,
        ...renderRuntimeTypes(type.members, indent + 4),
        `${padding}  ],`,
        `${padding}},`,
      ];
  }
}

function containsInputFile(
  type: TelegramSchemaType,
  typeDefinitions: ReadonlyMap<string, readonly TelegramSchemaType[]>,
  visitedReferences = new Set<string>(),
): boolean {
  switch (type.kind) {
    case 'array':
      return containsInputFile(type.element, typeDefinitions, visitedReferences);
    case 'input-file':
      return true;
    case 'literal':
    case 'primitive':
      return false;
    case 'reference': {
      if (visitedReferences.has(type.name)) return false;
      const definition = typeDefinitions.get(type.name);
      if (definition === undefined) return false;
      const nestedReferences = new Set(visitedReferences).add(type.name);
      return definition.some((member) =>
        containsInputFile(member, typeDefinitions, nestedReferences),
      );
    }
    case 'union':
      return type.members.some((member) =>
        containsInputFile(member, typeDefinitions, visitedReferences),
      );
  }
}

function renderUnionMembers(members: readonly TelegramSchemaType[]): string {
  return members.map(renderType).join(' | ');
}

function renderType(type: TelegramSchemaType): string {
  switch (type.kind) {
    case 'array':
      return `ReadonlyArray<${renderType(type.element)}>`;
    case 'input-file':
      return 'InputFile';
    case 'literal':
      return JSON.stringify(type.value);
    case 'primitive':
      return renderPrimitive(type.name);
    case 'reference':
      return type.name;
    case 'union':
      return renderUnionMembers(type.members);
  }
}

function renderPrimitive(name: TelegramSchemaPrimitive): string {
  switch (name) {
    case 'boolean':
      return 'boolean';
    case 'float':
    case 'integer':
      return 'number';
    case 'string':
      return 'string';
    case 'true':
      return 'true';
  }
}

function toPascalCase(name: string): string {
  return `${name[0]!.toUpperCase()}${name.slice(1)}`;
}

function toCamelCase(name: string): string {
  return name.replace(/_([a-z0-9])/g, (_, character: string) => character.toUpperCase());
}
